// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_Example
{
    public partial class Director
    {
        public Director()
        {
            Movies = new HashSet<Movie>();
        }

        public string DirectorName { get; set; }
        public int DirectorId { get; set; }


        public override string ToString()
        {
            return DirectorName;
        }
        public virtual ICollection<Movie> Movies { get; set; }
    }
}